name: q
version: '1.6.3-1'
summary: run SQL directly on CSV or TSV files
description: |
 q is a command line tool that allows direct execution of SQL-like queries on
 CSVs/TSVs (and any other tabular text files). q treats ordinary files as
 database tables, and supports all SQL constructs, such as WHERE, GROUP BY,
 JOINs etc. It supports automatic column name and column type detection, and
 provides full support for multiple encodings.
confinement: strict
grade: stable

apps:
  q:
    command: q

parts:
  q:
    plugin: dump
    source: https://github.com/harelba/q
    source-type: git
    source-tag: 1.6.3
    stage-packages:
      - python
